spring:
  datasource:
    url: jdbc:mysql://localhost:3306/msa_step02_order?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

#RestTemplate이 참조하는 설정값
# 서비스 디스커버리 설정
# payment-service의 이름은 spring.application.name을 기반으로 작성
service:
  payment:
    url: http://payment-service/payments

server:
  port: 8080

# cloud config 테스트용 설정 값
custom:
  message: "변경된 메시지 - TEST 환경입니다."
  version: "1.0.0"
